# Generated by Django 4.1.7 on 2023-03-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrections', '0003_customuser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_request_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
